// Barrel export of all service interfaces and shared types
export type { IAuthService } from './auth.interface';
export type { IInterventionsService } from './interventions.interface';
export type { IUsersService } from './users.interface';
export type { IDispatchService, DispatchResult, DispatchAttempt } from './dispatch.interface';
export type { IPaymentService, PaymentAuthorization, PaymentProvider, AuthorizationParams, AuthorizationResult, CaptureResult } from './payment.interface';
export type { IQuotesService, QuoteLine, QuoteInput, QuoteSummary } from './quotes.interface';
export type { IRatingsService, Rating } from './ratings.interface';
export type { IMessagesService, InterventionMessage } from './messages.interface';
export type { IScheduleService, TechnicianSchedule, ScheduleOverride } from './schedule.interface';
export type { ITechniciansService, TechnicianWithLocation, NearbyTechnician, EligibleTechnician } from './technicians.interface';
export type { IServicesService, Service } from './services.interface';
export type { IHistoryService } from './history.interface';
export type { IPhotosService } from './photos.interface';
export type { IWorkPhotosService, WorkPhoto, WorkPhotoType } from './work-photos.interface';
export type { IRevenueService, RevenueStats, WeeklyStats, PerformanceStats as RevenuePerformanceStats, PaymentPeriod, MonthlyPayout } from './revenue.interface';
export type { IStatisticsService, DailyStats, CategoryStats, StatusStats, StatisticsPerformanceStats, TechnicianStats } from './statistics.interface';
export type { IConfigurationService, DispatchAlgorithmConfig, ConfigurationHistoryEntry } from './configuration.interface';
export type { ICancellationService, CancellationResult } from './cancellation.interface';
export type { IPartnersService, PartnerApplicationData } from './partners.interface';
export type { IRolesService, AppRole, UserRoleRecord, ManagerPermissions } from './roles.interface';
export type { IGeocodingService } from './geocoding.interface';
export type { IPerformanceService, TechnicianPerformance, PerformanceTrend, ZoneStats, PeriodType, DateRange } from './performance.interface';
export type { IPricingService, PriorityMultiplier } from './pricing.interface';
export type { IQuoteModificationsService, QuoteModification, QuoteModificationItem, CreateQuoteModificationInput } from './quote-modifications.interface';
export type { IPayoutsService } from './payouts.interface';
export type { IDisputesService } from './disputes.interface';
export type { ISiteSettingsService, SiteSetting } from './site-settings.interface';
export type { INotificationsService, WelcomeNotificationInput } from './notifications.interface';
export type { IStorageService } from './storage.interface';
export type { IQuestionnaireService } from './questionnaire.interface';
export type { IInvoiceService } from './invoice.interface';
